### PR TITLE
feat: add alert group name

### PR DESCRIPTION
**Pull request by arturodilecce**
Adds the possibility to specify a `group_name` attribute on all Monitor Alert resources. This helps in the UI to group together similar alerts.

### CODE REVIEW

**Comment by hrabalvojta** [comment]
Are you aware that this pull request does not work as advertised?

**Comment by arturodilecce** [comment]
> 

Do you mean because of the missing `_ = data.Set("group_name", alert.GroupName) ` in the `alertToResourceData` function?

**Review by madchicken — APPROVED** [review]

**Comment by tembleking** [comment]
I am missing some tests that prove the behavior, and guarantee that the resource can be created, updated and removed successfully.
Please take a look at other tests to see how they are created :)

**Comment by arturodilecce** [comment]
@tembleking I've added the `group_name` attribute to some of the already existing testAcc for the alerts. thank you for suggesting that.

**Comment by arturodilecce** [comment]
closing in favor of #190

**Pull request closed without merging**
