### PR TITLE
fix(secure-onboarding) Update the cloudauth pb.go files

### PR DESCRIPTION
**Pull request by ravinadhruve10**
Fix summary:
--------------
Update the cloudauth go files to support newly added `providerAlias` field.

Testing done:
-----------------
Validated with the acceptance tests on staging.

### CODE REVIEW

**Review by mdkulkarni15 — APPROVED** [review]

**Review by haresh-suresh — APPROVED** [review]

**Comment by haresh-suresh** [comment]
Will this require a version update in our onboarding apis ?

**Review by cgeers — APPROVED** [review]
are we also going to enable `DiscardUnknown`?

**Comment by ravinadhruve10** [comment]
> Will this require a version update in our onboarding apis ?

yes

**Comment by ravinadhruve10** [comment]
> are we also going to enable `DiscardUnknown`?

Done.

**Pull request merged**
