### PR TITLE
Allow type to be specified for alert resources

### PR DESCRIPTION
**Pull request by jon-ruckwood**
Default to `MANUAL` when not set explicitly.

Type `PROMETHEUS` can be used to specify an alert with a PromQL expression.

### CODE REVIEW

**Comment by jon-ruckwood** [comment]
I came across an issue after an `terraform import` of a Prometheus-based alert. I found that whilst the import was successful, but any subsequent `apply` would fail with a `Wrong grammar for condition` error from the API. 

This was down to having type hardcoded as `MANUAL`.

**Comment by DenysChekirda** [comment]
@nkraemer-sysdig May I ask you to review this PR, please? Thanks

**Review by nkraemer-sysdig — APPROVED** [review]
LGTM!

**Comment by nkraemer-sysdig** [comment]
cc @nestorsalceda @wideawakening

**Comment by tembleking** [comment]
Hello @jon-ruckwood, thank you for the contribution!

I recently merged #129 which adds a new resource that supports PromQL Alerts, which IMO allows the resources grow at a different pace, as the product evolves.

I will close this PR since it's now duplicated, but I just wanted to highlight that any other future contributions are welcome and very appreciated :smiley:

**Pull request closed without merging**
