### PR TITLE
Update to compliance v2 task

### PR DESCRIPTION
**Pull request by aq17**
Change terraform deploys to create compliance v2 task instead of benchmarks v2 task

https://sysdig.atlassian.net/browse/SSPROD-10400

### CODE REVIEW

**Review by nkraemer-sysdig — COMMENTED** [review]
Doesn't the model need to change as well? The request/response bodies are different between the two endpoints aren't they?

**Comment by aq17** [comment]
> Doesn't the model need to change as well? The request/response bodies are different between the two endpoints aren't they?

Don't think so, looks like the new endpoint did a good job of adhering to the old schema for benchmarks (going based off the docs)

**Review by nkraemer-sysdig — APPROVED** [review]

**Comment by aq17** [comment]
@nestorsalceda @tembleking @wideawakening would any of you be familiar with the failing acceptance tests?

**Comment by nestorsalceda** [comment]
I'm checking with @tembleking and we think it might be a dependencies problem.

We are going to update and rerun this check

Thank you folks!

**Comment by nestorsalceda** [comment]
It worked, please merge if you need to :)

**Pull request merged**
