### PR TITLE
Added support of custom headers for Webhook notifications

### PR DESCRIPTION
**Pull request by DenysChekirda**
Right now there is no way to add custom headers into Webhook notifications which leads into problem to add password/token secured endpoints.

This PR adds an optional argument `additional_headers` for `sysdig_monitor_notification_channel_webhook` resource.

Example usage:
```
resource "sysdig_monitor_notification_channel_webhook" "k8s-worker" {
  name                      = "Test_Channel"
  enabled                   = true
  url                       = "https://secured.example.com"
  notify_when_ok            = false
  notify_when_resolved      = false
  send_test_notification    = false
  
  # New optional argument
  additional_headers        = {
    "Authentication": "Bearer TOKEN",
  }
}
```

### CODE REVIEW

**Comment by DenysChekirda** [comment]
@nkraemer-sysdig May I ask you to review this PR, please? Thanks

**Comment by nkraemer-sysdig** [comment]
It looks to me like this functionality might already exist: 

https://github.com/sysdiglabs/terraform-provider-sysdig/blob/master/sysdig/internal/client/monitor/client.go#L39-L43

https://github.com/sysdiglabs/terraform-provider-sysdig/blob/master/sysdig/sysdig_clients.go#L47-L54

https://github.com/sysdiglabs/terraform-provider-sysdig/blob/master/sysdig/provider.go#L45-L49

It looks like you can simply specify `extra_headers` when creating the sysdig provider like:
```
provider "sysdig" {
  sysdig_secure_url          = https://secure.sysdig.com
  sysdig_secure_api_token    = xxxx-xxxxxxxx-xxxx
  extra_headers = {
      "header_1": "value_1"
  }
}
```

**Comment by DenysChekirda** [comment]
@nkraemer-sysdig Correct me if I'm wrong, but `extra_headers` is related to create a client connection to self hosted instance of sysdig or any other instance of sysdig which requires to have any specific HTTP headers.

Meanwhile mine PR is related to creation of Webhook notifications channels and adding custom/specific HTTP headers which used to send a request to Webhook

**Review by nkraemer-sysdig — APPROVED** [review]
Oh, these headers are a _property_ of the webhook that will be created, that makes much more sense! Sorry for the confusion, this looks good to me!

**Comment by tembleking** [comment]
Hello @DenysChekirda, thank you for your contribution.
I am missing some testing in this PR that ensures the resource is working properly with the API.
Other than that, it looks great to me. Once the tests are in place, I will review it again, and we can get this merged. :slightly_smiling_face:

**Comment by DenysChekirda** [comment]
Hello @tembleking , just to clarify, you are referring to add `additional_headers` to https://github.com/sysdiglabs/terraform-provider-sysdig/blob/master/sysdig/resource_sysdig_monitor_notification_channel_webhook_test.go
or you mean to share output results as well as any screenshots?
Thanks

**Comment by tembleking** [comment]
@DenysChekirda I would add a new step like https://github.com/sysdiglabs/terraform-provider-sysdig/blob/31a53bbcb9cae4aba9b0dbbb01db6c51eb9ce31d/sysdig/resource_sysdig_monitor_notification_channel_webhook_test.go#L30-L32 and https://github.com/sysdiglabs/terraform-provider-sysdig/blob/31a53bbcb9cae4aba9b0dbbb01db6c51eb9ce31d/sysdig/resource_sysdig_monitor_notification_channel_webhook_test.go#L42-L52
that uses the new `additional_headers` field, just to make sure the headers are correctly added. If you can share additional screenshots, that'd be great, but it's not required :slightly_smiling_face: 
We only require automated tests to prove the functionality is working properly, and are not broken by either a change in the code or an update in the API.

**Comment by DenysChekirda** [comment]
@tembleking Thanks! 
Added test for webhook channel with additional headers.

**Comment by tembleking** [comment]
Thank you @DenysChekirda, I will review it and merge if everything's all right :)

**Comment by tembleking** [comment]
Hi @DenysChekirda, congrats, because the tests seems to be passing for the creation, but are now broken by the import test. 
I propose you two solutions for this:

```diff
diff --git a/sysdig/resource_sysdig_monitor_notification_channel_webhook_test.go b/sysdig/resource_sysdig_monitor_notification_channel_webhook_test.go
index 550d5ad..608315e 100644
--- a/sysdig/resource_sysdig_monitor_notification_channel_webhook_test.go
+++ b/sysdig/resource_sysdig_monitor_notification_channel_webhook_test.go
@@ -34,7 +34,7 @@ func TestAccMonitorNotificationChannelWebhook(t *testing.T) {
 				Config: monitorNotificationChannelWebhookWithNameWithAdditionalheaders(rText()),
 			},
 			{
-				ResourceName:      "sysdig_monitor_notification_channel_webhook.sample-webhook",
+				ResourceName:      "sysdig_monitor_notification_channel_webhook.sample-webhook2",
 				ImportState:       true,
 				ImportStateVerify: true,
 			},

```
or

```diff
diff --git a/sysdig/resource_sysdig_monitor_notification_channel_webhook_test.go b/sysdig/resource_sysdig_monitor_notification_channel_webhook_test.go
index 550d5ad..e3987e0 100644
--- a/sysdig/resource_sysdig_monitor_notification_channel_webhook_test.go
+++ b/sysdig/resource_sysdig_monitor_notification_channel_webhook_test.go
@@ -30,14 +30,14 @@ func TestAccMonitorNotificationChannelWebhook(t *testing.T) {
 			{
 				Config: monitorNotificationChannelWebhookWithName(rText()),
 			},
-			{
-				Config: monitorNotificationChannelWebhookWithNameWithAdditionalheaders(rText()),
-			},
 			{
 				ResourceName:      "sysdig_monitor_notification_channel_webhook.sample-webhook",
 				ImportState:       true,
 				ImportStateVerify: true,
 			},
+			{
+				Config: monitorNotificationChannelWebhookWithNameWithAdditionalheaders(rText()),
+			},
 		},
 	})
 }

```

**Comment by tembleking** [comment]
Thank you for the contribution @DenysChekirda, all seems to be working now!
I am merging this now, it will be available in the next release :smile:

**Pull request merged**
